accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "ISC",
    "OpenSSL",
    "Zlib",
    "MPL-2.0"
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
