# Project policies.
#
# These policies can be enforced using `cargo deny check`.

[licenses]
# Don't allow code with an unclear license.
unlicensed = "deny"

# Don't allow "copylefted" licenses unless they're listed below.
copyleft = "deny"

# Allow common non-restrictive licenses.
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "CC0-1.0"]

# Many organizations ban AGPL-licensed code
# https://opensource.google/docs/using/agpl-policy/
deny = ["AGPL-3.0"]

# Some slightly odder licenses. ISC is an unrestrictive license but unusual, and
# MPL-2.0 is long and complicated "copyleft" license that's less strict than the
# GPL. 
exceptions = [
    { name = "rdrand", allow = ["ISC"] },
    { name = "slog-json", allow = ["MPL-2.0"] },
]

[bans]
# Allow multiple versions of any crate for now, according to cargo's usual
# policy. We can refine this later.
multiple-versions = "allow"
