[package]
name = "schemaconv"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
common_failures = "0.1.1"
env_logger = "0.5.13"
log = "0.4.5"
schemaconvlib = { path = "../schemaconvlib" }
serde = "1.0.79"
serde_json = "1.0.32"
structopt = "0.2.10"
url = "1.7.1"
