[package]
name = "schemaconvlib"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
diesel = { version = "1.3.3", features = ["postgres"] }
failure = "0.1.2"
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"
url = "1.7.1"
