[package]
name = "dbcrossbarlib"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]
build = "build.rs"
edition = "2018"

license = "(Apache-2.0 OR MIT)"

[build-dependencies]
peg = "0.5"

[dependencies]
csv = "1.0.5"
diesel = { version = "1.3.3", features = ["postgres"] }
failure = "0.1.2"
lazy_static = "1.2.0"
log = "0.4.5"
native-tls = "0.2.2"
pipe = "0.1.0"
postgres = { version = "0.15.2", features = ["with-native-tls"] }
regex = "1.1.0"
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"
try_from = "0.3.2"
url = "1.7.1"
