[package]
name = "dbcrossbarlib"
version = "0.2.0-alpha.10"
authors = ["Eric Kidd <git@randomhacks.net>"]
build = "build.rs"
edition = "2018"

description = "Library for copying data between databases (pre-release)"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/faradayio/dbcrossbar"
documentation = "https://docs.rs/dbcrossbarlib/"

[build-dependencies]
peg = "0.5"

[dev-dependencies]
slog-async = "2.3.0"
slog-envlogger = "2.1.0"
slog-term = "2.4.0"

[dependencies]
bitflags = "1.1.0"
byteorder = "1.3.1"
bytes = "0.4.11"
cast = "0.2.2"
chrono = "0.4.6"
csv = "1.0.5"
diesel = { version = "1.3.3", features = ["postgres"] }
failure = "0.1.2"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
geo-types = "0.4"
# We use 0.15 instead of 0.16, because 0.16 requires features that are only
# available in nightly Rust, and we don't want to rely on nightly Rust for
# anything but `#![features(async_await)]`.
geojson = "0.15.0"
hex = "0.3.2"
itertools = "0.8.0"
lazy_static = "1.2.0"
log = "0.4.5"
native-tls = "0.2.2"
rand = "0.7"
regex = "1.1.0"
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"
tokio-postgres = "0.4.0-rc.2"
tokio-postgres-native-tls = "0.1.0-rc.1"
slog = "2.4.1"
strum = "0.15.0"
strum_macros = "0.15.0"
tempdir = "0.3.7"
tokio = "0.1.22"
tokio-process = "0.2.4"
try_from = "0.3.2"
url = "2.1.0"
uuid = "0.7.4"
walkdir = "2.2.9"
wkb = "0.4"
