[book]
authors = ["Eric Kidd"]
language = "en"
multilingual = false
src = "src"
title = "Using dbcrossbar"
description = "dbcrossbar copies tabular data between PostgreSQL, BigQuery, CSV and many other databases and formats."

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html]
git-repository-url = "https://github.com/dbcrossbar/dbcrossbar"
git-repository-icon = "fa-github"
theme = "src/theme"
