[book]
authors = ["Eric Kidd"]
language = "en"
multilingual = false
src = "src"
title = "Using dbcrossbar"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html]
git-repository-url = "https://github.com/dbcrossbar/dbcrossbar"
git-repository-icon = "fa-github"
theme = "src/theme"
