[package]
name = "dbcrossbar"
version = "0.0.13"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

description = "Program for copying data between databases (pre-release)"
license = "Apache-2.0 OR MIT"
readme = "../README.md"
repository = "https://github.com/faradayio/dbcrossbar"
documentation = "https://docs.rs/dbcrossbarlib/"

[dev-dependencies]
cli_test_dir = "0.1.5"
difference = "2.0"

[dependencies]
clap = { version = "2.32.0", features = ["wrap_help"] }
common_failures = "0.1.1"
env_logger = "0.6"
failure = "0.1.2"
log = "0.4.5"
openssl = "0.10.16" # Needed to prevent link errors.
openssl-probe = "0.1.2"
dbcrossbarlib = { path = "../dbcrossbarlib", version = "0.0.13" }
serde = "1.0.79"
serde_json = "1.0.32"
slog = { version = "2.4.1", features = ["max_level_trace", "release_max_level_trace"] }
slog-async = "2.3.0"
slog-envlogger = "2.1.0"
slog-term = "2.4.0"
structopt = "0.2.10"
structopt-derive = "0.2.14"
# Lock exact version to work around some nightly Rust breakage.
tokio = { version = "=0.1.18", features = ["async-await-preview"] }
url = "1.7.1"
